sudo: false
language: scala
scala:
  - 2.11.12
  - 2.13.1
  - 2.12.10
jdk:
  - openjdk11
services:
  - memcached
  - redis
before_install:
  - git fetch --tags
install:
  - make travis-install
before_script:
  - make travis-run

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    - stage: test
      name: Check formatting
      scala: 2.13.1
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalafmtSbtCheck
    - stage: test
      name: Compile the docs
      scala: 2.12.10
      script: sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
    - stage: release
      scala: 2.13.1
      script: sbt ci-release
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
after_script:
  - make stop
