sudo: false
language: scala
scala:
  - 2.11.12
  - 2.13.0
  - 2.12.8
jdk:
  - oraclejdk8
services:
  - memcached
  - redis
install:
  - make travis-install
before_script:
  - make travis-run
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalafmtSbtCheck coverage test ++2.12.8 doc/tut
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
after_script:
  - make stop
